_prj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dataentries/", include("app_dataentries.urls")),
    path("celery-test", views.celery_test, name="celery_test"),
    path("", views.index, name="index"),
    # Registration & Login urls
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # app emails
    path("emails/", include("app_emails.urls")),
    # app sandbox
    path("sandbox/", include("app_sandbox.urls")),
    # app profiles
    path("profiles/", include("app_profiles.urls")),
    # app reports
    path("reports/", include("app_reports.urls")),
    # app products
    path("products/", include("app_products.urls")),
    # app areas
    path("areas/", include("app_areas.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_dataentries/urls.py
from django.urls import path

from app_dataentries import views

app_name = "dataentries"

urlpatterns = [
    path("", views.index, name="index"),
    path("import-data", views.import_data, name="import_data"),
    path("export-data", views.export_data, name="export_data"),
]

app_emails/urls.py
from django.urls import path

from app_emails import views

app_name = "emails"

urlpatterns = [
    path("send-email/", views.send_email, name="send_email"),
    path("<int:email_id>/view", views.view_email, name="view_email"),
]

app_dataentries/models.py
from django.db import models


class Student(models.Model):
    roll_no = models.CharField(max_length=10)
    name = models.CharField(max_length=25)
    age = models.IntegerField()

    def __str__(self) -> str:
        return self.name


class Customer(models.Model):
    customer_name = models.CharField(max_length=20)
    country = models.CharField(max_length=20)

    def __str__(self):
        return self.customer_name


class Employee(models.Model):
    employee_id = models.IntegerField()
    employee_name = models.CharField(max_length=25)
    designation = models.CharField(max_length=25)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    retirement = models.DecimalField(max_digits=10, decimal_places=2)
    other_benefits = models.DecimalField(max_digits=10, decimal_places=2)
    total_benefits = models.DecimalField(max_digits=10, decimal_places=2)
    total_compensation = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.employee_name + " - " + self.designation

app_dataentries/views.py
# Create your views here.
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect, render

# from app_dataentries.tasks import import_data_task
from app_dataentries.tasks import export_data_task, import_data_task
from app_dataentries.utils import check_csv_errors, get_all_custom_models
from app_uploads.models import Upload


def index(request):
    context = {}
    return render(request, "app_dataentries/index.html", context)


def import_data(request):
    """Import data"""
    if request.method == "POST":
        file_path = request.FILES.get("file_path")
        model_name = request.POST.get("model_name")

        # store this file inside the Upload model
        upload = Upload.objects.create(file=file_path, model_name=model_name)

        # # construct the full path
        relative_path = str(upload.file.url)
        base_url = str(settings.BASE_DIR)
        file_path = base_url + relative_path

        # check for the csv errors
        try:
            check_csv_errors(file_path, model_name)
        except Exception as e:
            messages.error(request, str(e))
            return redirect("dataentries:import_data")

        # handle the import data task here
        import_data_task.delay(file_path, model_name)

        # show the message to the user
        messages.success(
            request,
            "Your data is being imported, you will be notified once it is done.",
        )
        return redirect("dataentries:import_data")
    else:
        custom_models = get_all_custom_models()
        context = {
            "custom_models": custom_models,
        }
    return render(request, "app_dataentries/import_data.html", context)


def export_data(request):
    if request.method == "POST":
        model_name = request.POST.get("model_name")

        # call the export data task
        export_data_task.delay(model_name)

        # show the message to the user
        messages.success(
            request,
            "Your data is being exported, you will be notified once it is done.",
        )
        return redirect("dataentries:export_data")
    else:
        custom_models = get_all_custom_models()
        context = {
            "custom_models": custom_models,
        }
    return render(request, "app_dataentries/export_data.html", context)

app_dataentries/templates/app_dataentries/export_data.html
{% extends "base.html" %}
{% block content %}
  <div class="container mt-5 alert-success shadow"
       style="max-width: 600px;
              padding: 50px;
              border-radius: 10px">
    <h3 class="text-center">Export Data From Database Tables</h3>
    <form action="{% url 'dataentries:export_data' %}"
          method="post"
          style="max-width: 600px;
                 margin:auto;
                 padding-top: 50px">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="model_name">Select Database Table</label>
        <select name="model_name" class="form-control" required>
          <option value="" disabled selected>Select</option>
          {% for model in custom_models %}<option value="{{ model }}">{{ model }}</option>{% endfor %}
        </select>
      </div>
      <div class="form-group">
        <input type="submit" value="Export Data" class="btn btn-success">
      </div>
    </form>
  </div>
{% endblock content %}

app_dataentries/templates/app_dataentries/import_data.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
  <h3 class="text-center">Import Data To Database Tables</h3>
{% endblock page_header %}
{% block content %}
  <form action="{% url 'dataentries:import_data' %}"
        method="post"
        enctype="multipart/form-data"
        style="max-width: 600px;
               margin:auto;
               padding-top: 50px">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="file_path">Upload CSV File</label>
      <input type="file" name="file_path" class="form-control" required>
    </div>
    <div class="form-group mb-3">
      <label for="model_name">Select Database Table</label>
      <select name="model_name" class="form-control" required>
        <option value="" disabled selected>Select</option>
        {% for model in custom_models %}<option value="{{ model }}">{{ model }}</option>{% endfor %}
      </select>
    </div>
    <div class="form-group">
      <input type="submit" value="Import Data" class="btn btn-primary">
    </div>
  </form>
{% endblock content %}

app_dataentries/templates/app_dataentries/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container" style="padding: 50px;margin-top: 5%;">
    {% if user.is_authenticated %}
      <div class="row pt-5">
        <!-- Import data -->
        <div class="col-md-4">
          <a href="{% url 'dataentries:import_data' %}"
             class="text-decoration-none text-dark">
            <div class="card alert-primary shadow bg-primary-subtle">
              <div class="card-header">
                <h4>Import Data</h4>
              </div>
              <div class="card-body">
                <p class="card-text">Imports data from CSV file to any table.</p>
              </div>
            </div>
          </a>
        </div>
        <!-- Export Data -->
        <div class="col-md-4">
          <a href="{% url 'dataentries:export_data' %}"
             class="text-decoration-none text-dark">
            <div class="card alert-success shadow bg-success-subtle">
              <div class="card-header">
                <h4>Export Data</h4>
              </div>
              <div class="card-body">
                <p class="card-text">Exports data from a specific table to a CSV file.</p>
              </div>
            </div>
          </a>
        </div>
        <!-- Bulk Emails -->
        <div class="col-md-4">
          <a href="{% url 'emails:send_email' %}"
             class="text-decoration-none text-dark">
            <div class="card alert-danger shadow bg-danger-subtle">
              <div class="card-header">
                <h4>Bulk Emails</h4>
              </div>
              <div class="card-body">
                <p class="card-text">Sends bulk emails to users</p>
              </div>
            </div>
          </a>
        </div>
      </div>
      <div class="row pt-5">
        <!-- Email Tracking -->
        <div class="col-md-4">
          <a href="{% url 'index' %}" class="text-decoration-none text-dark">
            <div class="card alert-warning shadow bg-warning-subtle">
              <div class="card-header">
                <h4>Email Tracking</h4>
              </div>
              <div class="card-body">
                <p class="card-text">Tracks emails and shows open and click rate</p>
              </div>
            </div>
          </a>
        </div>
        <!-- Compress Images -->
        <div class="col-md-4">
          <a href="{% url 'index' %}" class="text-decoration-none text-dark">
            <div class="card alert-danger shadow bg-info-subtle">
              <div class="card-header">
                <h4>Compress Images</h4>
              </div>
              <div class="card-body">
                <p class="card-text">Compresses Image files and reduces the size</p>
              </div>
            </div>
          </a>
        </div>
        <!-- Web Scraping -->
        <div class="col-md-4">
          <a href="{% url 'index' %}" class="text-decoration-none text-dark">
            <div class="card alert-warning shadow bg-body-secondary">
              <div class="card-header">
                <h4>Stock Market Analysis</h4>
              </div>
              <div class="card-body">
                <p class="card-text">Stock Market Analysis - Web Scraping</p>
              </div>
            </div>
          </a>
        </div>
      </div>
    {% else %}
      <div class="home-info">
        <h2 class="text-center">Automate the Boring Stuff with Django</h2>
        <p class="lead text-center text-muted">
          "Automate the Boring Stuff with Django" is a project-based course to build various tools using the Django framework to automate routine tasks, ranging from data processing to scheduling, and more.
          By leveraging Django's capabilities, users can streamline their workflows, saving time and enhancing productivity.
        </p>
        <div style="display: flex; justify-content: center;">
          <a href="{% url 'login' %}" class="btn btn-primary">LOGIN</a>
          &nbsp;<a href="{% url 'register' %}" class="btn btn-success">REGISTER</a>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock content %}