_prj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dataentries/", include("app_dataentries.urls")),
    path("celery-test", views.celery_test, name="celery_test"),
    path("", views.index, name="index"),
    # Registration & Login urls
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # app emails
    path("emails/", include("app_emails.urls")),
    # app sandbox
    path("sandbox/", include("app_sandbox.urls")),
    # app profiles
    path("profiles/", include("app_profiles.urls")),
    # app reports
    path("reports/", include("app_reports.urls")),
    # app products
    path("products/", include("app_products.urls")),
    # app areas
    path("areas/", include("app_areas.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_reports/urls.py
from django.urls import path

from app_reports import views

app_name = "reports"

urlpatterns = [
    path("", views.report_view, name="report_view"),
]

app_reports/models.py
import random

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from app_areas.models import ProductionLine
from app_products.models import Product

el = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
]
hours = [(str(x), str(x)) for x in range(1, 25)]


def random_code():
    random.shuffle(el)
    code = [str(x) for x in el[:12]]
    str_code = "".join(code)

    return str_code


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Report(models.Model):
    day = models.DateField(default=timezone.now)
    start_hour = models.CharField(max_length=2, choices=hours)
    end_hour = models.CharField(max_length=2, choices=hours)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="report")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    plan = models.PositiveIntegerField()
    execution = models.PositiveIntegerField()
    production_line = models.ForeignKey(ProductionLine, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_day(self):
        return self.day.strftime("%Y/%m/%d")

    def get_absolute_url(self):
        return reverse(
            "reports:update-view",
            kwargs={
                "production_line": self.production_line,
                "pk": self.pk,
            },
        )

    def __str__(self):
        return "{}-{}-{}".format(self.start_hour, self.end_hour, self.production_line)

    class Meta:
        ordering = ("-created",)


class ProblemReported(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    problem_id = models.CharField(
        max_length=12, unique=True, blank=True, default=random_code
    )
    breakdown = models.PositiveIntegerField()
    public = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    # objects = ProblemReportedManager()

    def __str__(self):
        return "{}-{}".format(self.category.name, self.description[:20])

    class Meta:
        verbose_name = "Problem Reported"
        verbose_name_plural = "Problems Reported"

app_reports/forms.py
from django import forms

from app_reports.models import ProblemReported, Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = "__all__"


class ProblemReportedForm(forms.ModelForm):
    class Meta:
        model = ProblemReported
        fields = "__all__"

app_reports/views.py
from django.shortcuts import render

from app_reports.forms import ProblemReportedForm, ReportForm


def report_view(request):
    """Report View"""

    form = ReportForm()
    pform = ProblemReportedForm()

    context = {
        "form": form,
        "pform": pform,
    }

    return render(request, "app_reports/report.html", context)

app_reports/templates/app_reports/report.html
{% extends "prj_profiles/base-profiles.html" %}
{% load crispy_forms_tags %}
{% block title %}
  report
{% endblock title %}
{% block content %}
  <!-- Modal -->
  <div class="modal fade"
       id="problemModal"
       tabindex="-1"
       role="dialog"
       aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Report problems</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">X</span>
          </button>
        </div>
        <form action="" method="post">
          {% csrf_token %}
          <div class="modal-body">
            {{ pform|crispy }}
            <input type="hidden" name="report_id" id="report_id">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" name="submitbtn1" class="btn btn-primary">Send</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="container bg-white shadow-lg rounded py-2">
    <div class="row">
      <div class="col-2">
        <form action="" method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit"
                  name="submitbtn2"
                  class="btn btn-primary w-100 shadow-sm mt-3">
            <i class="far fa-paper-plane pr-3"></i>Send
          </button>
        </form>
      </div>
      <div class="col-10">
        <div style="overflow-y:scroll;
                    height:85vh"
             class="w-100 bg-light rounded border">
          <table class="table">
            <thead class="thead-light">
              <tr class="text-center">
                <th scope="col">Day</th>
                <th scope="col">Start</th>
                <th scope="col">End</th>
                <th scope="col">Product</th>
                <th scope="col">Plan</th>
                <th scope="col">Execution</th>
                <th scope="col">Line</th>
                <th scope="col"></th>
                <th scope="col">Problems</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in object_list %}
                <tr class="text-center">
                  <td>{{ obj.get_day }}</td>
                  <td>{{ obj.start_hour }}</td>
                  <td>{{ obj.end_hour }}</td>
                  <td>{{ obj.product }}</td>
                  <td>{{ obj.plan }}</td>
                  <td>{{ obj.execution }}</td>
                  <td>{{ obj.production_line }}</td>
                  <td>
                    {% if obj.problemreported_set.all %}<div class="badge badge-danger">P</div>{% endif %}
                  </td>
                  <td class="fit">
                  <button class="btn btn-warning open-modal" data-toggle="modal" data-target="#problemModal" data-url={{ obj.id }}><i class="fas fa-exclamation-triangle"></i>
                </button>
              </td>
              <td class="fit">
                <a href="{{ obj.get_absolute_url }}">
                  <button class="btn btn-info">
                    <i class="far fa-edit"></i>
                  </button>
                </a>
              </td>
              <td class="fit">
                <a href="{% url 'reports:delete-view' pk=obj.id %}">
                  <button class="btn btn-danger">
                    <i class="fas fa-trash-alt"></i>
                  </button>
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>
<script>
$(".open-modal").on("click", function() {
    const r_id = $(this).attr("data-url")
    $("#report_id").val(r_id)
    console.log(r_id)
});

</script>
{% endblock content %}