_prj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dataentries/", include("app_dataentries.urls")),
    path("celery-test", views.celery_test, name="celery_test"),
    path("", views.index, name="index"),
    # Registration & Login urls
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # app emails
    path("emails/", include("app_emails.urls")),
    # app sandbox
    path("sandbox/", include("app_sandbox.urls")),
    # app profiles
    path("profiles/", include("app_profiles.urls")),
    # app reports
    path("reports/", include("app_reports.urls")),
    # app products
    path("products/", include("app_products.urls")),
    # app areas
    path("areas/", include("app_areas.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_dataentries/urls.py
from django.urls import path

from app_dataentries import views

app_name = "dataentries"

urlpatterns = [
    path("", views.index, name="index"),
    path("import-data", views.import_data, name="import_data"),
    path("export-data", views.export_data, name="export_data"),
]

templates/includes/alert.html
{% if messages %}
  <div class="messages" id="messages">
    {% for message in messages %}
      <div {% if message.tags %}class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
  </div>
{% endif %}

templates/includes/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "index" %}">Automate Boring <i class="fa-solid fa-bowl-food"></i></a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% comment %} <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
          <a class="nav-link btn btn-outline-success m-2" aria-current="page" href="{% url 'dataentries:import_data' %}">Import Data</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link btn btn-outline-success m-2" aria-current="page" href="{% url 'dataentries:export_data' %}">Export Data</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link btn btn-outline-success m-2" aria-current="page" href="{% url 'celery_test' %}">Celery Test</a>
        </li>
      </ul> {% endcomment %}
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ms-auto mb-2 mb-md-0">
        <!-- Authentication Links -->
        {% if user.is_authenticated %}
          <li class="nav-item d-flex align-items-center">
            {% if user.profile.photo %}
              <img src="{{ user.profile.photo.url }}"
                   alt="Profile"
                   style="width: 30px;
                          height: 30px;
                          border-radius: 50%;
                          margin-right: 5px">
            {% endif %}
            <span class="nav-text me-2">Welcome, <a href="#">{{ user.username }}</a></span>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "register" %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "login" %}">Login</a>
          </li>
        {% endif %}
      </ul>
      <!-- End of account related links -->
      {% if user.is_authenticated %}
        <form action="{% url "logout" %}" method='post'>
          {% csrf_token %}
          <button type="submit" class="btn btn-outline-secondary btn-sm">Logout</button>
        </form>
      {% endif %}
    </div>
  </div>
</nav>